name: QuickStatusSDC
version: '0.0.1-RELEASE'
main: com.github.white555gamer.quickstatussdc.QuickStatusSDC
api-version: 1.19
authors: [ WHERE_WHITE_, WHERE_WHITE_KUN, WHITE555Gamer ]
description: Quick Status Share and Development Commands.

commands:

  sharelocation:
    usage: |
      /ShareLocation
    description: |
      You can share your location on chat.

  quick_fullfood:
    usage: |
      /quick_fullfood
      /quick_fullfood < PlayerName >
    description: |
      You can quick recover food point.
    permission: op
    permission-message: "ERROR: No Operator Permissions."

  quick_fullhealth:
    usage: | 
      /quick_fullhealth
      /quick_fullhealth < PlayerName >
    description: |
      You can quick recover health point.
    permission: op
    permission-message: "ERROR: No Operator Permissions."

  quick_recovery:
    usage: |
      /quick_recovery
      /quick_recovery < PlayerName >
    description: |
      You can quick recover health and food point.
    permission: op
    permission-message: "ERROR: No Operator Permissions."
